### ISSUE TITLE
Which metrics is used for expected performance levels

### ISSUE THREAD

**Issue by chris-pn-dev** [GameTechDev/gpudetect#5]
Hi,
    Which metrics is used for evaluating expected performance levels (low, medium and high)? Only GFLOPS? Is memory bandwidth taken into consideration? Thanks.

**Comment by DaveBookout-Intel** [comment]
The expected performance level is mainly a placeholder. Within a generation, it's related to number of execution units and power. We hope to update the sample soon. Please let us know if you have feedback. Thanks.

**Comment by chris-pn-dev** [comment]
Got it. Hope for your update. Thanks!
